runtime: nodejs18
env: standard
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1
env_variables:
  DATABASE_URL: postgresql://postgres:123456@34.130.54.132:5432/test-db
